services:
  postgres:
    image: postgres:16
    container_name: workhub-postgres
    environment:
      POSTGRES_DB: workhub
      POSTGRES_USER: workhub
      POSTGRES_PASSWORD: workhub
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U workhub"]
      interval: 10s
      timeout: 5s
      retries: 10

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.1.7
    container_name: workhub-redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 512M
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:9092
      - --pandaproxy-addr
      - 0.0.0.0:8082
      - --advertise-pandaproxy-addr
      - redpanda:8082
    ports:
      - "9092:9092"
      - "9644:9644"
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -q 'Healthy:.*true'"]
      interval: 10s
      timeout: 5s
      retries: 20

  workhub-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workhub-app
    depends_on:
      redpanda:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      DB_HOST: postgres
      DB_USERNAME: workhub
      DB_PASSWORD: workhub
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./src/cfg/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./src/cfg/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./src/cfg/grafana/grafana.ini:/etc/grafana/grafana.ini