apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: workhub-workhub-app:latest
          imagePullPolicy: Never        # use local image, not DockerHub
          ports:
            - containerPort: 8080
