apiVersion: v1
kind: Secret
metadata:
  name: workhub-secret
type: Opaque
stringData:
  db-username: workhub
  db-password: workhub
  auth-secret-key: WorkHubWorkinghubbbbhfdhfgueusfuherfqwoeierf345vg43tv44vt5463