spring.application.name=WorkHub
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update

auth.secretKey=WorkHubWorkinghubbbbhfdhfgueusfuherfqwoeierf345vg43tv44vt5463